### ISSUE TITLE
PlatformIO release 1.0.0 broken

### ISSUE THREAD

**Issue by TheNitek** [bitbank2/bb_captouch#1]
I just stumbled about the PlatformIO releae of this lib being broken. It seems like the fix from https://github.com/bitbank2/bb_captouch/commit/df0ed5f421554c4278ed66615ce378d00ca9e818 has not been released yet, so it ends up in an compile error.

Would it be possible to create an updated release?

**Comment by bitbank2** [comment]
sure thing
