### ISSUE TITLE
V1.1.0 detects wrong touch chip - v1.0.2 is OK

### ISSUE THREAD

**Issue by Westcott1** [bitbank2/bb_captouch#2]
I have a Waveshare ESP32-S3-LCD-4.3 with a GT911 chip.
Everything works correctly with v1.0.2.
However, when I upgrade to v1.1.0 the chip is detected as an AXS15231 and touch no longer works.

Thanks for this library!
It's the only one that worked for me.

**Comment by bitbank2** [comment]
I disabled that code (latest commit). Give it a try.

**Comment by Westcott1** [comment]
Thanks, all working now!

**Comment by bitbank2** [comment]
ok, I'll do a new release with that removed

**Comment by Westcott1** [comment]
Hi Bitbank2,

Sorry to bother you again, but I updated to v1.1.1 and the the chip GT911 is detected as an AXS15231.

**Comment by bitbank2** [comment]
Sorry, I thought I had disabled all of the experimental code. Removed in release 1.1.2
