### ISSUE TITLE
CST820 datasheet?

### ISSUE THREAD

**Issue by chupocro** [bitbank2/bb_captouch#5]
Hi,

I was looking for but cound't even find a CST820's manufacturer, let alone a datasheet. Where did you find it to write the library?

Regards

**Comment by bitbank2** [comment]
I don't have access to the datasheet. Most cap touch sensors work the same way. I was able to make it work by looking at the register positions in someone else's code.

**Comment by chupocro** [comment]
I have a source code for CST820 driver from the documentation of `JC2432W328` display I mentioned here:

https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/discussions/200#discussioncomment-10078820

But it could be seen from the code the implemented functionality is only partial, that's why I've been looking for the datasheet.

The author of [this page](https://qiita.com/hi631/items/2fdc19d1e440f98330b1) mentioned your library and the library from some display's documentation too and he said:

(translated from Japanese)
> I found two types of CST820 libraries used for the touch panel. One is published as a library called bb_captouch. The other is included in the 24C demo program, cst820.cpp.
> Both support single-point touch, but other operations are unclear.
> bb_captouch supports two-point touch, but stops about 100ms after touch.
> - Some initialization is probably required, but the method written in cst820.cpp does not work.
> - cst820.cpp has a description of gestures, but this does not work either.
> - I guess the important parts will not be disclosed unless you sign a contract. I guess there's no other way.

Maybe the author of the code you used to write the library has the datasheet?

**Comment by bitbank2** [comment]
Not sure what to say. It's not on my to-do list at the moment. If you find the info, please let me know.
